package com.acme.model.vo.hello;

// Code generated by protoc-gen-bean. DO NOT EDIT.
// 2018-03-12 Mon 22:09:14 UTC+0800
//
//     hello.proto
//

import com.acme.model.vo.common.RspHead;
import com.acme.model.vo.hello.Greeting;
import ;


public class Hello {
    public RspHead header;
    public Greeting greeting;
    public String name;
    public byte[] sig;
    public Hello_Mark cool;
    
    @Override
    public String toString() {
        return "Hello{" +
                "header=" + header + ","
                "greeting=" + greeting + ","
                "name='" + name + '\'' + ","
                "sig=" + sig + ","
                "cool=" + cool + "}"
    }

    public class Mark {
        public int code;
        public String payLoad;
        
        @Override
        public String toString() {
            return "Mark{" +
                    "code=" + code + ","
                    "payLoad='" + payLoad + '\'' + "}"
        }
    }
}
