package com.acme.model.vo.hello;

// Code generated by protoc-gen-bean. DO NOT EDIT.
// 2018-03-13 Tue 19:54:26 UTC+0800
//
//     hello.proto
//

import com.acme.model.vo.hello.Hello;

import java.util.List;

public class World {
    public List<Hello> hello;
    
    @Override
    public String toString() {
        return "World{" +
                "hello=" + hello + "}"
    }
}
