package com.acme.model.vo.common;

// Code generated by protoc-gen-bean. DO NOT EDIT.
// 2018-03-14 Wed 01:29:21 UTC+0800
//
//     common.proto
//


public class AnotherMsg {
    public String text;
    public int value;
    
    @Override
    public String toString() {
        return "AnotherMsg{" +
                "text='" + text + '\'' + ","
                "value=" + value + "}"
    }
}
