package com.acme.model.vo.common;

// Code generated by protoc-gen-bean. DO NOT EDIT.
// 2018-03-13 Tue 19:54:26 UTC+0800
//
//     common.proto
//


public class RspHead {
    public String msg;
    public int errCode;
    
    @Override
    public String toString() {
        return "RspHead{" +
                "msg='" + msg + '\'' + ","
                "errCode=" + errCode + "}"
    }
}
