package com.acme.model.protobuf.converter;

// Code generated by protoc-gen-bean. DO NOT EDIT.
// 2018-03-13 Tue 19:54:26 UTC+0800
//
//     common.proto
//

import com.acme.model.protobuf.PbCommon;
import com.google.protobuf.InvalidProtocolBufferException;


public class CommonPb2JavaBean {
    public static RspHead toRspHead(byte[] data) {
        try {
            PbCommon.RspHead pbRspHead = PbCommon.RspHead.parseFrom(data);
            
            RspHead rspHead = new RspHead();
            rspHead.msg = pbRspHead.getMsg();
            rspHead.errCode = pbRspHead.getErrCode();
            
            return rspHead;
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
        
        return null;
    }
    
}
