package com.acme.model.protobuf.converter;

// Code generated by protoc-gen-bean. DO NOT EDIT.
// 2018-03-14 Wed 16:51:09 UTC+0800
//
//     common.proto
//

import com.acme.model.protobuf.PbCommon;
import com.acme.model.vo.common.AnotherMsg;
import com.acme.model.vo.common.RspHead;
import com.google.protobuf.InvalidProtocolBufferException;


public class CommonPb2JavaBean {
    public static RspHead toRspHead(byte[] data) {
        try {
            PbCommon.RspHead pbRspHead = PbCommon.RspHead.parseFrom(data);
            
            RspHead rspHead = new RspHead();
            rspHead.msgpbRspHead.getMsg();
            rspHead.errCodepbRspHead.getErrCode();
            
            return rspHead;
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
        
        return null;
    }
    
    public static AnotherMsg toAnotherMsg(byte[] data) {
        try {
            PbCommon.AnotherMsg pbAnotherMsg = PbCommon.AnotherMsg.parseFrom(data);
            
            AnotherMsg anotherMsg = new AnotherMsg();
            anotherMsg.textpbAnotherMsg.getText();
            anotherMsg.valuepbAnotherMsg.getValue();
            
            return anotherMsg;
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
        
        return null;
    }
    
}
