package com.acme.model.protobuf.converter;

// Code generated by protoc-gen-bean. DO NOT EDIT.
// 2018-03-14 Wed 01:29:21 UTC+0800
//
//     common.proto
//

import com.acme.model.protobuf.PbCommon;
import com.google.protobuf.InvalidProtocolBufferException;


public class CommonPb2JavaBean {
    public static RspHead toRspHead(byte[] data) {
        try {
            PbCommon.RspHead pbRspHead = PbCommon.RspHead.parseFrom(data);
            
            RspHead rspHead = new RspHead();
            rspHead.msg = pbRspHead.getMsg();
            rspHead.errCode = pbRspHead.getErrCode();
            
            return rspHead;
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
        
        return null;
    }
    
    public static AnotherMsg toAnotherMsg(byte[] data) {
        try {
            PbCommon.AnotherMsg pbAnotherMsg = PbCommon.AnotherMsg.parseFrom(data);
            
            AnotherMsg anotherMsg = new AnotherMsg();
            anotherMsg.text = pbAnotherMsg.getText();
            anotherMsg.value = pbAnotherMsg.getValue();
            
            return anotherMsg;
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
        
        return null;
    }
    
}
