package com.acme.model.protobuf.converter;

// Code generated by protoc-gen-bean. DO NOT EDIT.
// 2018-03-14 Wed 16:51:09 UTC+0800
//
//     hello.proto
//

import com.acme.model.protobuf.PbCommon;
import com.acme.model.protobuf.PbHello;
import com.acme.model.vo.common.AnotherMsg;
import com.acme.model.vo.common.RspHead;
import com.acme.model.vo.hello.Greeting;
import com.acme.model.vo.hello.Hello;
import com.acme.model.vo.hello.World;
import com.google.protobuf.InvalidProtocolBufferException;

import java.util.ArrayList;
import java.util.List;

public class HelloPb2JavaBean {
    public static Hello toHello(byte[] data) {
        try {
            PbHello.Hello pbHello = PbHello.Hello.parseFrom(data);
            
            Hello hello = new Hello();
            hello.header = CommonPb2JavaBean.toHeader(pbHello.getHeader().toByteArray());
            hello.greetingpbHello.getGreeting();
            hello.namepbHello.getName();
            hello.sigpbHello.getSig();
            
            return hello;
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
        
        return null;
    }
    
    public static World toWorld(byte[] data) {
        try {
            PbHello.World pbWorld = PbHello.World.parseFrom(data);
            
            World world = new World();
            world.hello = new ArrayList<>();
            for (int i = 0; i < pbWorld.getHelloCount(); i++) {
                PbHello.Hello hello_ = pbWorld.getHello(i);
                world.hello.add(toHello(hello_.toByteArray()));
            }
            world.elements = new ArrayList<>();
            for (int i = 0; i < pbWorld.getElementsCount(); i++) {
                PbCommon.AnotherMsg anotherMsg_ = pbWorld.getElements(i);
                world.elements.add(CommonPb2JavaBean.toAnotherMsg(anotherMsg_.toByteArray()));
            }
            
            return world;
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
        
        return null;
    }
    
}
